
def calculate_financial_ratios(income_statement: dict, balance_sheet: dict) -> dict:
    """
    Calculates profitability and solvency ratios from the statements
    already generated by statement_generator.py. Returns None for any
    ratio that can't be calculated (e.g. division by zero), rather
    than a misleading number.
    """
    total_revenue = income_statement.get("total_revenue", 0)
    total_expenses = income_statement.get("total_expenses", 0)
    net_profit = income_statement.get("net_profit", 0)
    total_liabilities = balance_sheet.get("total_liabilities", 0)
    total_equity = balance_sheet.get("total_equity", 0)

    # Cost of Sales specifically, needed for Gross Profit Margin
    cost_of_sales = sum(
        item["amount"] for item in income_statement.get("expenses", [])
        if item.get("category") == "Cost of Sales"
    )

    ratios = {}

    # Gross Profit Margin = (Revenue - Cost of Sales) / Revenue
    if total_revenue > 0:
        gross_profit = total_revenue - cost_of_sales
        ratios["gross_profit_margin"] = round((gross_profit / total_revenue) * 100, 2)
    else:
        ratios["gross_profit_margin"] = None

    # Net Profit Margin = Net Profit / Revenue
    if total_revenue > 0:
        ratios["net_profit_margin"] = round((net_profit / total_revenue) * 100, 2)
    else:
        ratios["net_profit_margin"] = None

    # Debt to Equity = Total Liabilities / Total Equity
    if total_equity > 0:
        ratios["debt_to_equity"] = round(total_liabilities / total_equity, 2)
    else:
        ratios["debt_to_equity"] = None

    # Expense breakdown by category, as a percentage of total expenses
    expense_breakdown = {}
    if total_expenses > 0:
        by_category = {}
        for item in income_statement.get("expenses", []):
            cat = item["category"]
            by_category[cat] = by_category.get(cat, 0) + item["amount"]
        for cat, amount in by_category.items():
            expense_breakdown[cat] = round((amount / total_expenses) * 100, 2)

    return {
        "gross_profit_margin": ratios["gross_profit_margin"],
        "net_profit_margin": ratios["net_profit_margin"],
        "debt_to_equity": ratios["debt_to_equity"],
        "expense_breakdown_pct": expense_breakdown,
        "note": (
            "Current Ratio and other liquidity ratios are not yet available, "
            "since current vs long-term assets are not separately tracked "
            "in the current version."
        ),
    }