def calculate_financial_ratios(income_statement: dict, balance_sheet: dict) -> dict:
    """
    Calculates profitability, solvency, and liquidity ratios from the statements
    already generated by statement_generator.py. Returns None for any
    ratio that can't be calculated (e.g. division by zero), rather
    than a misleading number.
    """
    total_revenue = income_statement.get("total_revenue", 0)
    total_expenses = income_statement.get("total_expenses", 0)
    net_profit = income_statement.get("net_profit", 0)
    total_liabilities = balance_sheet.get("total_liabilities", 0)
    total_equity = balance_sheet.get("total_equity", 0)

    # Calculate Current Assets and Current Liabilities for Liquidity
    current_assets = sum(
        float(item.get("amount") or 0)
        for item in balance_sheet.get("assets", [])
        if item.get("category") in {
            "Cash & Cash Equivalents",
            "Trade Receivables",
            "Inventory",
            "Other Current Asset",
        }
    )
    current_liabilities = sum(
        float(item.get("amount") or 0)
        for item in balance_sheet.get("liabilities", [])
        if item.get("category") in {"Trade Payables", "Current Liability"}
    )

    # Cost of Sales specifically, needed for Gross Profit Margin
    cost_of_sales = sum(
        float(item.get("amount") or 0)
        for item in income_statement.get("expenses", [])
        if item.get("category") == "Cost of Sales"
    )

    ratios = {}

    # Gross Profit Margin = (Revenue - Cost of Sales) / Revenue
    if total_revenue and total_revenue > 0:
        gross_profit = total_revenue - cost_of_sales
        ratios["gross_profit_margin"] = round((gross_profit / total_revenue) * 100, 2)
    else:
        ratios["gross_profit_margin"] = None

    # Net Profit Margin = Net Profit / Revenue
    if total_revenue and total_revenue > 0:
        ratios["net_profit_margin"] = round((net_profit / total_revenue) * 100, 2)
    else:
        ratios["net_profit_margin"] = None

    # Debt to Equity = Total Liabilities / Total Equity
    if total_equity and total_equity > 0:
        ratios["debt_to_equity"] = round(total_liabilities / total_equity, 2)
    else:
        ratios["debt_to_equity"] = None

    # Current Ratio = Current Assets / Current Liabilities
    if current_liabilities and current_liabilities > 0:
        ratios["current_ratio"] = round(current_assets / current_liabilities, 2)
    else:
        ratios["current_ratio"] = None

    # Expense breakdown by category, as a percentage of total expenses
    expense_breakdown = {}
    if total_expenses and total_expenses > 0:
        by_category = {}
        for item in income_statement.get("expenses", []):
            cat = item.get("category", "Uncategorized")
            by_category[cat] = by_category.get(cat, 0) + float(item.get("amount") or 0)
        for cat, amount in by_category.items():
            expense_breakdown[cat] = round((amount / total_expenses) * 100, 2)

    return {
        "gross_profit_margin": ratios["gross_profit_margin"],
        "net_profit_margin": ratios["net_profit_margin"],
        "debt_to_equity": ratios["debt_to_equity"],
        "current_ratio": ratios["current_ratio"],
        "expense_breakdown_pct": expense_breakdown,
    }